### ISSUE TITLE
Expected amb8465 on /dev/ttyACM0 but found unknown instead, ignoring it! - after cold boot

### ISSUE THREAD

**Issue by antcroissant** [weetmuts/wmbusmeters#323]
Closed #322 a little early. It still happens once after cold boot, after that it is working fine, even unplugging/replugging the the stick or start/stop/restart the unit. Weird. New debug attached.
[debug_boot.log](https://github.com/weetmuts/wmbusmeters/files/6962865/debug_boot.log)

**Comment by antcroissant** [comment]
I did some more testing and it seems that cold/warm booting or unplugging/replugging the stick to the same or a different port has nothing to do with this issue. It is pretty random when the stick is correctly initialized. About 50% of the time it works on the first try, other times not. Replugging into the same physical port, when the the stick was correctly initialized once on that port, seems to works substantially better, but fails eventually after doing some more replugging.

```sudo killall -HUP wmbusmetersd``` after the stick is not detected, always works in any situation. Really weird. I tried changing all usleep in "wmbus_amb8465.cc" to ```usleep(10000*100);```, but this did not work either. Well, I am not a programmer and was wild guessing anyway.

**Comment by weetmuts** [comment]
Ok, what happens if you revert the usleep change and instead change both count >= 4 and count > 3 to count > 10 ?

**Comment by antcroissant** [comment]
I change wmbus_am865.cc like below, did a clean rebuild and did my testing.
```
--- src/wmbus_amb8465.cc.orig	2021-08-15 13:56:56.000000000 +0200
+++ src/wmbus_amb8465.cc	2021-08-15 14:04:03.039120715 +0200
@@ -631,7 +631,7 @@
             // Perhaps the dongle needs to wake up. Lets try again in 100 ms.
             usleep(1000*100);
             count ++;
-            if (count >= 4)
+            if (count >= 11)
             {
                 // Tried and failed 3 times.
                 debug("(amb8465) failed to sent query! Giving up!\n");
@@ -640,7 +640,7 @@
                 return AccessCheck::NotThere;
             }
         }
-    } while (sent == false && count < 4);
+    } while (sent == false && count < 11);
 
     // Wait for 100ms so that the USB stick have time to prepare a response.
     usleep(1000*100);
@@ -650,7 +650,7 @@
     count = 1;
     for (;;)
     {
-        if (count > 3)
+        if (count > 10)
         {
             verbose("(amb8465) are you there? no.\n");
             serial->close();
```
Unfortunately, this doesn't help, same behaviour as before.

One thing I noticed:

When it works, it always works on the first try (reading response... 1)
If not, all following "reading response" will fail (received binary "")

I have a logfile attached, where I plugged in the stick and it worked,
then unplugged it, waited a little and replugged it, which then failed.

Thank you!

[debug_with_count-10.log](https://github.com/weetmuts/wmbusmeters/files/6988137/debug_with_count-10.log)

**Comment by weetmuts** [comment]
Ok, new hypothesis. It could be that the amb8465 chip has a very small buffer, when receiving data from the computer, no hardware/software flow control, etc. 

So it is still sending bytes to the computer, ie the latest received telegram, when wmbusmeters sends the probe query.
The probe query gets truncated due to the minimal buffer inside the chip, and can no longer be interpreted by
the amb8465 chip, when it is done transmitting the latest telegram. This is what it looks like from your latest log.

I pushed a (hopeful) fix where the detection code really clears out any incoming telegrams, before it sends the detect signal.

Please test!

**Comment by antcroissant** [comment]
Sorry, still no luck. New debug log attached with a failed attempt and what happens after "killall -HUP wmbusmetersd".
[debug.log](https://github.com/weetmuts/wmbusmeters/files/7015230/debug.log)
[debug_hub.log](https://github.com/weetmuts/wmbusmeters/files/7015231/debug_hub.log)

**Comment by antcroissant** [comment]
I'm still wild guessing, but it seems, that the clearing of the buffer never happens, because there is always an additional empty binary send from the stick (after the usually multiple long lines of "received binary").

```(serial) received binary ""```

I forced to clear the buffer, even when it is empty and it seems indeed empty:

```
(serialtty) opened /dev/ttyACM0 fd 4 (detect amb8465)
(serial) received binary "00004B6E080000426C9F2CCB086E0000C2086CBF27326CFFFF006D3100B428F83D4493443807883523377277"
(serial) received binary "0867934423040D0000200C05651922004C0570250700426C9F2CCC080565192200C2086CBF27326CFFFF046D3003B428122F446850764282436180A0019F29000040310000000000000000000000000000000000000000000000000000000000E22F446850754282436180A0019F29920040310E01000000000000000000000000000000006F9F3B3A19000004000000E63D449344390788352337722714086793442304F70000200C05805606004C0520100200426C9F2CCC080580560600C2086CBF27326CFFFF046D3103B428122F446850865325827062A0009F29CD0140314000000003030605050602030506050304040403050202030203030302122A4468502349300194087A800010259152BC9CB47D4592CA85761D31A480230F0FA68576D4854946D1CE1233446850181712606980A0019F293B0040311B00E607DF07000000000000000000000000000000001209070501000000000000E233446850354311606980A0819F2909084031AD050E072307000600060002000673587F8965A583EFADA39ABC9F6D73680C03001234446850234930019480A20F9F29B40740317904012407320700000100000000000E2E07494637455B3B58688D1F325807000000122F446850754282436180A0019F29920040310E01000000000000000000000000000000006F9F3B3A19000004000000EA324493443929092735087A290000200B6E8002004B6E320100426C9F2CCB086E800200C2086CBF27326CFFFF046D3604B428E83D4493444107883523377228140867934423040B0000200C05815211004C0580060400426C9F2CCC080581521100C2086CBF27326CFFFF046D3503B428122F446850865325827062A0009F29CD014031400000000303060505060203050605030404040305020203020303030212"
(serial) received binary ""
(amb8465) cleared 0 bytes from serial buffer
(amb8465) sending 6 bytes attempt 0
(serial /dev/ttyACM0) sent "FF0A02008077"
(amb8465) sent 6 bytes OK
(serial) EVENT thread interrupted
(amb8465) reading response... 1
(serial) received binary ""
(amb8465) reading response... 2
(serial) received binary ""
(amb8465) reading response... 3
(serial) received binary ""
(amb8465) are you there? no.
(serialtty) closed /dev/ttyACM0 (detect amb8465)
```

**Comment by weetmuts** [comment]
Ah, no worries about that. The read from the serial port is non-blocking, so if there has not arrived any data after waiting 100ms it will report an empty string.

The next step is to resend the query message after the response is empty and do that 2-3 times before giving up.
Can you test such a code change? You can simplify the code and just give up if the send fails, no need to loop that.

**Comment by weetmuts** [comment]
clear thouroughly
LOOP:
  send FF0A02008077
  wait 100ms
  read buffer
 if empty then wait another 200ms, then LOOP but give up after 3 tries.
decode data.

**Comment by weetmuts** [comment]
I have a memory of a problem trying to detect the amber stick after trying to detect the im871a first.
I hade to start with amb8465 detection because the im871a is not upset by the amb probing.
But if I started with the im871a probing then I hade to add a 1-2 second delay before probing the amb8465 to have it 
respond properly. This is quite odd since they are using different serial speeds....

**Comment by antcroissant** [comment]
I don't think i am able to do that. I don't have a real clue about coding. Doing some patches and fiddling with some lines of code are fine, but anything else i still have to learn. Sorry.

**Comment by weetmuts** [comment]
No worries. But the best would be if I can reproduce the problem myself. Are you doing the test on a raspberry pi?
What os etc..?

**Comment by antcroissant** [comment]
I'm currently building and running wmbusmeters with archlinux (x86_64) on my trusted Thinkpad.

a quick and dirty way on arch:
```
$ pacman -Syu base base-devel devtools rtl-sdr git
$ git clone https://github.com/weetmuts/wmbusmeters.git
$ cd wmbusmeters/
$ ./configure 
$ make
```
I also work on a Arch AUR Package, which I plan to maintain in the hope it will adapted to official arch some day.

This is the stick i'm using:

```
kernel: usb 1-2: new full-speed USB device number 9 using xhci_hcd
kernel: usb 1-2: New USB device found, idVendor=03eb, idProduct=204b, bcdDevice= 1.01
kernel: usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=220
kernel: usb 1-2: Product: µ-Line FE
kernel: usb 1-2: Manufacturer: www.mueller-electronic.com powered by Atmel®
kernel: usb 1-2: SerialNumber: xxxxxxxxxxxxxxxxxxxx
```
I edited the serial out, because I don't know how the manufacturer feels about this.

Thank you for your help!

**Comment by weetmuts** [comment]
Any news on this? I have been working on the amb8465 driver recently, do you still experience this problem?

**Comment by BIBOLV** [comment]
Closing due to inactivity. Please reopen issue if problem is still persistent.

**Comment by Anas92230** [comment]
> do you still experience

Hello I have a problem with metis-ii i have nothing in compare with my nooelec usb (rtl2832u)
